### ISSUE TITLE
Questions in regard to Apple open sourcing FoundationDB

### ISSUE THREAD

**Issue by mindcrash** [Doxense/foundationdb-dotnet-client#62]
Since Apple very recently decided to open FoundationDB again to the general public (and open source it aswell) I was wondering about two things:

1. How difficult would it be to update and build the library for use with the latest C client library (in FoundationDB 5.1)? 
2. How difficult would it be to make the library .NET Standard 2.0 compliant (so it can be used with the .NET Core 2 runtime?)

**Comment by KrzysFR** [comment]
I'm currently in the process of updating and testing with the new version (5.1.5), and so far everything just works fine, so that is a good news!

1. Technically, you only need to update the `fdb_c.dll` (using the latest MSI from https://www.foundationdb.org/download/ ) without the need to rebuild the .NET binding (I just did that and all tests pass). The only issue is that right now the .NET binding targets API v200 (v2.x) by default, because at the time FDB v3.x was just released. I'm looking at changing the default to API v500 since probably nobody is using FDB v3.x in production with .NET right now, and everyone will probably install the latest v5.1.5 anyway.

2. The code base of this repo hasn't changed in the last 3 years, but it has been recycled as the base of another framework (not available on GitHub), which is .NET Standard 2.0 compliant. 

The .NET binding was written a long time ago (~2013) in a pre-.NET Core era, and I had to implement a lot of infrastructure that was missing in .NET 4.0/4.5 at the time (Tuples, Slice, IAsyncEnumerable<T>, ...). A lot of these things are now available in .NET 4.6.x (Tuples, ...), or are coming in .NET Core 2.0/2.1 preview (Span<T>, IAsyncEnumerable<T>, etc...).

I've also completely overhauled the whole Tuple and Subspace API (used to generate keys). This work was never merged in this repo, and is API breaking.

The question is whether to keep using this old implementations, or overhaul everything to immediately start integration with the new Span<T> and C# 7.x hotness, and this way get rid of all the pre-.NET Core code, and start on a clean slate?

**Comment by mindcrash** [comment]
Could be a good idea to start integrating with .NET Core 2.1 considering the new featureset, plus you probably get a ton of deep performance enhancements for free applied throughout the BCL.

**Comment by KrzysFR** [comment]
I think that targeting .NET Standard 2.0, and at least C# 7.2 would be a good start.

For .NET Core 2.1, the main feature for me is performance, but I still need to be compatible with .NET 4.6.x at the moment. I can still use `Span<T>` via the NuGet package, but there is a potential issue: spans are JIT optimized in .NET Core 2.1 so they are very fast. But with .NET Framework, they are not recognized by the JIT and are a LOT slower (especially `Memory<T>`).

I'm not sure if the .NET Framework 4.7.2 will include the JIT optimizations of .NET Core 2.1 or not (looking at the timing, 4.7.2 is available in preview for some time now, while the Span API was changed a lot in the last few weeks (DangerousGetPinnableReference renamed, things moved around in MemoryMarshal/MemoryExtensions, etc....)

My fear is that if we start using `Span<T>`, but it is slow in current version of .NET Framework, this could greatly impact performance...  Anyway I have opened an issue (#65) about this.
