### ISSUE TITLE
OSS-ing custom layers on top of FDB .NET Client (a nuget package to refer to)

### ISSUE THREAD

**Issue by abdullin** [Doxense/foundationdb-dotnet-client#77]
What are the plans for release of the official nuget package?

I'd like to build and share a few custom .NET layers on top of this library (e.g. event store, commit log). The usual approach is to pull the core library as a dependency. However, it seems, currently the `FoundationDB.Client` library is blocked by SkuVault and there are no alternatives.

Are there any plans for the nuget distribution (e.g. wait to get the nuget package or use a different name)?

PS: I was the one who published that nuget package a while ago while working at SkuVault. Didn't expect this decision to come out sideways. I'm sorry.

**Comment by KrzysFR** [comment]
The plan is to finish support for some 4.x and 5.x features (I'm currently working on VersionStamps), which should be done soon, and then release a 5.1.5-alpha nuget package.

I'm bumping the version straight to 5.1 to be in synch with the FoundationDB version itself (will be easier to know what version of the binding you need to support new features introduced in 5.2 or 6.0 etc...)

It will still be marked "alpha" because I fear that there will be a few breaking changes required here and there as we start using new features and discover corner cases (what's happening with VersionStamp right now).

I'm also currently in the process of integrating the FoundationDB.Client library back into our product, which is already using some of the parts (Slice, Tuples, etc...) so I'm having tons of conflict (same types with same namespace but on different assemblies). I'll probably need to move some files around, and may need to change a few internal namespaces as well.

Moving forward, I think that I will try to version the client along with the database, adding support for new features when they come along. And probably only consider major API change for mew major versions.

**Comment by abdullin** [comment]
It looks like you have a lot on your plate right now!

While you are moving towards the alpha version, do you mind if I pushed `FoundationDB.Client.dll` into some temporary nuget, while clearly saying that this is experimental, based on the doxense but completely unsupported? E.g. `Doxense.Fdb.Draft` (or whatever name you prefer).

This nuget could be pulled down as soon as you release 5.1.5-alpha nuget package.

By the way, I saw your comment in the source code about version stamps. I wanted to have that feature for years, but didn't expect the implementation to be tricky.

**Comment by KrzysFR** [comment]
I have published version [5.1.0-alpha1](https://github.com/Doxense/foundationdb-dotnet-client/releases/tag/5.1.0-alpha1) on the [NuGet Gallery]( https://www.nuget.org/packages/FoundationDB.Client/5.1.0-alpha1) !

It is still subject to API changes, though it should hopefully only be minor things (probably VersionStamps once I get some feedback).

**Comment by KrzysFR** [comment]
I have setup a MyGet feed at https://www.myget.org/feed/Packages/foundationdb-dotnet-client that should produce a build and package for each commit to master. Thanks to the folks at MyGet for providing a free open-source licence!

There is also the existing AppVeyor build at https://ci.appveyor.com/project/KrzysFR/foundationdb-dotnet-client 

The remaining issue for build servers will be how to run unit tests on these? They would need a running instance of FoundationDB, but I don't think they allow installing arbitrary code on their build severs.

Maybe having a running cluster instance in AWS/Azure, but 1) it's not free, 2) how do we secure these?

**Comment by abdullin** [comment]
Regarding FDB testing. I'm planning to upgrade my old packer+terraform scripts that enable spinning up a FoundationDB cluster on AWS (and then tearing it down). Given that, I might be able to setup a build pipeline on travis-ci to run FDB client tests on mac and linux.

Unfortunately travis-ci doesn't support windows environment, if I'm not mistaken. However, probably we could set up a dedicated windows build machine to handle that (I'll ask my current employer, when we get to that).

**Comment by abdullin** [comment]
NB: Tried to setup travis-ci to build and test the client library on Linux/OSX. Unfortunately, it didn't work out of the box (e.g. some projects are still targeting desktop). I'll need to investigate that later.

The nuget package works fine on OSX, though!

**Comment by KrzysFR** [comment]
Hopefully the nuget packages and myget nightly feed will allow anyone to build layers on top of this.
